### ISSUE TITLE
Sextile year calculation

### ISSUE THREAD

**Issue by popy-dev** [Nephos/french_cal#1]
The sextile year calculation is the one used by the julian calendar, while, at this time, the gregorian calendar was already in use, so it's safe to guess that the same calculation would have been used.

I don't use this language, so I'm not confident enougth to make a PR, but I think that this could work :

```
  def self.is_sextile?(year : Int)
    year % 4 == 0 AND year % 100 != 0 OR year % 400 == 0
  end
```

And, about the SEXTILE_FIRST constant, a possible implementation could be (in pseudo language, as I don't know the syntax) :

```
  def self.is_sextile?(year : Int)
   if (year < 21) {
      year = year + 1; // so that 3, 7, 11 ... will be calculated as 4, 8, 12 as sextile
   }

    year % 4 == 0 AND year % 100 != 0 OR year % 400 == 0
  end

```

Good continuation :)

**Comment by Nephos** [comment]
I never though someone would be interested in this project :O

**Comment by Nephos** [comment]
Anyway thanks, I had given up on this project few hours after beginning but I might try to finish it someday with these informations :)

**Comment by popy-dev** [comment]
Je suis tombé sur ce projet (et d'autres) en faisant des recherches pour mon implémentation en PHP.
Après j'ai fait ça à ma sauce, mais j'ai pris la peine d'ouvrir quelques tickets par ci par là.

Et comme ça, on sera prêts pour la prochaine révolution !
